version: "3.2"
services:
 
  nodejs:
    build: 
      context: .
    image: rafaelgiordano/ibm_dev_test
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=rafaelgiordano-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=linksibm
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3000:3000"
     
    container_name: rafaelgiordano-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=linksibm
    container_name: rafaelgiordano-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=rafaelgiordano-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
     
    container_name: rafaelgiordano-phpmyadmin-app
networks:
  frontend:
  backend: